config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  post 'welcome/conectar'
  resources :pessoas
  
  match '/auth/:provider/callback' => 'sessions#callback', via: 'get'
  match '/signout' => 'sessions#destroy', via: 'get', as: :signout

end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.nickname = auth['info']['nickname']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end
  end


  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:name, :last_name, :email, :company, :job_title, :phone, :website)
    end
end

app/controllers/sessions_controller.rb
require 'net/http'

class SessionsController < ApplicationController

  def callback
    @auth = request.env['omniauth.auth']
    
    version = getVersion(URI("#{@auth['credentials']['instance_url']}/services/data/"))

    user = User.find_by_provider_and_uid(@auth['provider'],['uid']) || User.create_with_omniauth(@auth)
    session[:user_id] = user.id


     # uri_query = @auth['info']['urls']['sobjects']
     # uri_query["{version}"] = "#{version}"
#   
     # select = '?q=SELECT+name+from+Account'
#      
     # uri = URI("#{uri_query}+#{select}")
    
    
     # Net::HTTP.new(host || URI.parse(self.instance_url).host, 443).tap do |http|
        # http.use_ssl = true
        # http.ca_file = self.ca_file if self.ca_file
        # http.verify_mode = self.verify_mode if self.verify_mode
      # end
    
    
    # Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
      # request = Net::HTTP::Get.new uri
#     
      # result = http.request request # Net::HTTPResponse object
      # puts result
    # end
    
    # result = JSON.parse(Net::HTTP.get(uri_query+select))
    # puts result

  # session[:result] = http_get("https://na17.salesforce.com/services/data/v22.0/sobjects/")
  # puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
  # puts session[:result]
  # puts "@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    
    
    redirect_to root_path, :notice => 'Welcome to Salesforce!!'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
  
  private
  def getVersion(uri)
    sales = JSON.parse(Net::HTTP.get(uri))
    sales.last['version']
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
  
  def conectar
    # @client = Databasedotcom::Client.new("config/databasedotcom.yml")
    # @client.authenticate request.env['omniauth.auth']
    # puts "========================="
    # names = @client.query("SELECT Name FROM Account") 
    # puts "========================="
    # puts names
    # puts "========================="
  end
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rdstationdesafio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Job title</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.name %></td>
        <td><%= pessoa.last_name %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.company %></td>
        <td><%= pessoa.job_title %></td>
        <td><%= pessoa.phone %></td>
        <td><%= pessoa.website %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pessoa.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @pessoa.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pessoa.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @pessoa.company %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @pessoa.job_title %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pessoa.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @pessoa.website %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>

app/views/welcome/conectar.html.erb
<h1>oi</h1>
<% if current_user %>
	<p>conectado</p>
	
	
<% else %>
	<p>desconectou</p>
<% end %>

app/views/welcome/index.html.erb
<%= form_tag :action => 'conectar' do %>
  <%= submit_tag 'Conectar' %>
<% end %>

<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
  

 
<% else %>
  <%= link_to "Sign in with Salesforce", "/auth/salesforce" %>
<% end %>
<br/>
<p id="notice"><%= notice %></p>